### ISSUE TITLE
SRE applications fail with "authentication request to the wrong tenant"

### ISSUE THREAD

**Issue by kargakis** [openshift/azure-misc#104]
time="2018-10-12T09:50:46Z" level=info msg="azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions?api-version=2016-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"unauthorized_client\",\"error_description\":\"AADSTS700016: Application with identifier 'XXXXXXXX-7c99-40d3-8ea2-24641c598776' was not found in the directory 'XXXXXX-63ba-4af7-8f33-e7333e421980'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant\\r\\nTrace ID: XXXXXXXX-5d14-431a-ba86-9e0207cf5100\\r\\nCorrelation ID: XXXXXXXXX-c3e7-4c48-92c8-96b18bdc1257\\r\\nTimestamp: 2018-10-12 09:50:46Z\",\"error_codes\":[700016],\"timestamp\":\"2018-10-12 09:50:46Z\",\"trace_id\":\"XXXXXXXX-5d14-431a-ba86-9e0207cf5100\",\"correlation_id\":\"XXXXXXXXX-c3e7-4c48-92c8-96b18bdc1257\"}"

/kind bug

**Comment by kargakis** [comment]
Same issue for grafana and the dashboard.

cc @jim-minter

**Comment by jim-minter** [comment]
Believe this is a straight case of invalid credentials, closing.
